name: vessel-anomaly-detection
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - setuptools
  - conda-libmamba-solver
  # sci
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  # cli
  - click
  - gh
  # data
  - pandas
  - polars
  # sci-data
  - netcdf4
  - intake
  - xarray
  - numcodecs
  - pint
  - pyarrow
  - zarr
  # encoding
  - cchardet
  # web
  - beautifulsoup4
  # cloud
  - fsspec
  # plot
  - matplotlib
  - descartes
  - pillow
  - seaborn
  # jupyter
  - ipython
  - jupyter
  - jupyterlab
  - ipywidgets
  - jupyterlab-lsp
  - jupyter-lsp
  - voila
  # spatial
  - shapely
  - geopandas
  - pyproj
  - cartopy
  - contextily
  - rasterio
  - rio-cogeo
  - rio-tiler
  - rioxarray
  - pip:
      # deep learning
    - torch
    - torchvision
    - torchaudio
    - tensorboard
    - dask[complete]
    - dask-jobqueue
    - dask_labextension
    - dask-geopandas
    - movingpandas
    - networkx
    - folium
    - datashader
    - holoviews
    - geoviews
    - bokeh
    - panel
    - python-dotenv
    - featuretools
    - tsfresh
    - hvplot
    - Bottleneck
    - -e .
